In [1]:
import os
import numpy as np
import pandas as pd
import time
import os.path as osp
import re
from sklearn.model_selection import train_test_split
from collections import Counter
np.set_printoptions(threshold=np.inf)
import DataHelper
import importlib
from collections import Counter
importlib.reload(DataHelper)

<module 'DataHelper' from 'C:\\Users\\dxeec\\Desktop\\EcoForest-master\\DataHelper.py'>

In [5]:
data_path = osp.join(".\\datasetes","letter","letter-recognition.data")

In [6]:
print(data_path)

.\datasetes\letter\letter-recognition.data


In [7]:
with open(data_path) as f:
    rows = [row.strip().split(',') for row in f.readlines()]

In [8]:
print(rows)

[['T', '2', '8', '3', '5', '1', '8', '13', '0', '6', '6', '10', '8', '0', '8', '0', '8'], ['I', '5', '12', '3', '7', '2', '10', '5', '5', '4', '13', '3', '9', '2', '8', '4', '10'], ['D', '4', '11', '6', '8', '6', '10', '6', '2', '6', '10', '3', '7', '3', '7', '3', '9'], ['N', '7', '11', '6', '6', '3', '5', '9', '4', '6', '4', '4', '10', '6', '10', '2', '8'], ['G', '2', '1', '3', '1', '1', '8', '6', '6', '6', '6', '5', '9', '1', '7', '5', '10'], ['S', '4', '11', '5', '8', '3', '8', '8', '6', '9', '5', '6', '6', '0', '8', '9', '7'], ['B', '4', '2', '5', '4', '4', '8', '7', '6', '6', '7', '6', '6', '2', '8', '7', '10'], ['A', '1', '1', '3', '2', '1', '8', '2', '2', '2', '8', '2', '8', '1', '6', '2', '7'], ['J', '2', '2', '4', '4', '2', '10', '6', '2', '6', '12', '4', '8', '1', '6', '1', '7'], ['M', '11', '15', '13', '9', '7', '13', '2', '6', '2', '12', '1', '9', '8', '1', '1', '8'], ['X', '3', '9', '5', '7', '4', '8', '7', '3', '8', '5', '6', '8', '2', '8', '6', '7'], ['O', '6', '13', '4'

In [9]:
n_datas = len(rows)
X = np.zeros((n_datas, 16), dtype=np.float32)
y = np.zeros(n_datas, dtype=np.int32)

In [10]:
for i, row in enumerate(rows):
    X[i, :] = list(map(float, row[1:]))
    y[i] = ord(row[0]) - ord('A')

【row[1:]】row是一行，一维数组，1：代表从下标1开始取到结尾。

【ord()】 函数是 chr() 函数（对于8位的ASCII字符串）或 unichr() 函数（对于Unicode对象）的配对函数，它以一个字符（长度为1的字符串）作为参数，返回对应的 ASCII 数值

【X[i,:]】X是二维数组，i,:代表下标i行，从0开始取到结尾。

In [11]:
print(X)

[[ 2.  8.  3.  5.  1.  8. 13.  0.  6.  6. 10.  8.  0.  8.  0.  8.]
 [ 5. 12.  3.  7.  2. 10.  5.  5.  4. 13.  3.  9.  2.  8.  4. 10.]
 [ 4. 11.  6.  8.  6. 10.  6.  2.  6. 10.  3.  7.  3.  7.  3.  9.]
 [ 7. 11.  6.  6.  3.  5.  9.  4.  6.  4.  4. 10.  6. 10.  2.  8.]
 [ 2.  1.  3.  1.  1.  8.  6.  6.  6.  6.  5.  9.  1.  7.  5. 10.]
 [ 4. 11.  5.  8.  3.  8.  8.  6.  9.  5.  6.  6.  0.  8.  9.  7.]
 [ 4.  2.  5.  4.  4.  8.  7.  6.  6.  7.  6.  6.  2.  8.  7. 10.]
 [ 1.  1.  3.  2.  1.  8.  2.  2.  2.  8.  2.  8.  1.  6.  2.  7.]
 [ 2.  2.  4.  4.  2. 10.  6.  2.  6. 12.  4.  8.  1.  6.  1.  7.]
 [11. 15. 13.  9.  7. 13.  2.  6.  2. 12.  1.  9.  8.  1.  1.  8.]
 [ 3.  9.  5.  7.  4.  8.  7.  3.  8.  5.  6.  8.  2.  8.  6.  7.]
 [ 6. 13.  4.  7.  4.  6.  7.  6.  3. 10.  7.  9.  5.  9.  5.  8.]
 [ 4.  9.  6.  7.  6.  7.  8.  6.  2.  6.  5. 11.  4.  8.  7.  8.]
 [ 6.  9.  8.  6.  9.  7.  8.  6.  5.  7.  5.  8.  8.  9.  8.  6.]
 [ 5.  9.  5.  7.  6.  6. 11.  7.  3.  7.  3.  9.  2.  7.  5. 

In [13]:
print(y)

[19  8  3 13  6 18  1  0  9 12 23 14  6 12 17  5 14  2 19  9  9  7 18 14
  9  2 12 22  7  6 11 11 23  1 12  6 14 15  6  4 23  4 23  6 21 23 22  6
 17 18 24 11 24  9 18 16 16  3  2 11 13  2  4 23  7 11  7  4 24  7 16 16
 16  9  9  3 17 12  0 13 12 15  2 15 13 22 21 21 12  4 13 24 22 14 13  7
 14 13  7 20 24 18 18 19  2 21 19 10  3 22  8  4  5  8  7 20  2  5  0 25
 23 13 17  1  1 20  9  5 12  7  0 14  4 20  0 23 18  9 10  8 15 19  2  7
  0 11 19  0 21 20  8 25 21 12 11 14  1  0 10  7 19 22  5  0  4 12  1 12
 24 21 18  2  7 20 15 25  4 13 15  7 19  1 20 18  5  9 17  4 15  8 10  3
  1  7 12 15 14 18 10 21  5 24  3 25 16 18  1 10 21  1 24 14 25 11  9 25
  0 11  9 16 13 25  4  9  3 14 11 21 23  9 13  7  0 15  0  5 23  3 21 15
  5 15 24 22 15  9  4 18  4  1  8 18 18  2 12 15 17 20 20  3 20  9 25  5
 21 12 20  1 11 19  3 19 14 19 20  3 17  6  3 18 18 12 12  3 25 22  2 10
  9  0  3  2 21 18  5  0  1 13 20 18 16  5  5 23  0  1 14  9  7 12  8 22
 13  0 18 15  3 12 19 11 23  6  3  4 13  6 21  0  4

In [15]:
X_train, y_train = X[:16000], y[:16000]
X_test, y_test = X[16000:], y[16000:]

In [16]:
print("X.shape:", X_train.shape, "y.shape:", y_train.shape)
print("X.shape:", X_test.shape, "y.shape:", y_test.shape)

X.shape: (16000, 16) y.shape: (16000,)
X.shape: (4000, 16) y.shape: (4000,)


In [17]:
Counter(y)

Counter({19: 796,
         8: 755,
         3: 805,
         13: 783,
         6: 773,
         18: 748,
         1: 766,
         0: 789,
         9: 747,
         12: 792,
         23: 787,
         14: 753,
         17: 758,
         5: 775,
         2: 736,
         7: 734,
         22: 752,
         11: 761,
         15: 803,
         4: 768,
         21: 764,
         24: 786,
         16: 783,
         20: 813,
         10: 739,
         25: 734})